### ISSUE TITLE
For ASQA, how to reproduce the baseline?

### ISSUE THREAD

**Issue by AllenShow** [AkariAsai/self-rag#43]
Hi! Thanks for your great work.
I try to reproduce the baseline for ASQA using Llama-2-7b-hf, like this:

python run_baseline_lm.py \
--model_name meta-llama/Llama-2-7b-hf \
--input_file eval_data/asqa_eval_gtr_top100.json \
 --max_new_tokens 300 --metric match \
--result_fp output/test_out_ASQA_Llama-2-7b-hf_300_Retrieval-augmented  --task qa --mode retrieval --prompt_name "prompt_no_input_retrieval"    --world_size 8

However, the error was returned :
Traceback (most recent call last):
  File "run_baseline_lm.py", line 230, in <module>
    main()
  File "run_baseline_lm.py", line 128, in main
    retrieval_result = item["ctxs"][:args.top_n]
KeyError: 'ctxs'

Could you please help to fix it?

**Comment by Haoang97** [comment]
I also met this issue when using my own retrieval data. The key 'ctxs' possibly refer to "contexts". The data items in asqa_eval_gtr_top100.json don't always have the key 'ctxs'. To fix this issue, maybe you have modify this code block to fit ASQA dataset.
