### ISSUE TITLE
How to fix the bug about 'local variable 'pred' referenced before assignment'?

### ISSUE THREAD

**Issue by AllenShow** [AkariAsai/self-rag#50]
in run_short_form.py

```
 if len(results) == 1:
        postprocessed_pred = postprocess_answer_option_conditioned(pred)
        return postprocessed_pred, results, do_retrieve

```

> Traceback (most recent call last):
> File "run_short_form.py", line 371, in
> main()
> File "run_short_form.py", line 329, in main
> pred, results, do_retrieve = generate(
> File "run_short_form.py", line 313, in generate
> return call_model_rerank_w_scores_batch(prompt, evidences=evidences, model=model, max_new_tokens=max_new_tokens,
> File "run_short_form.py", line 179, in call_model_rerank_w_scores_batch
> postprocessed_pred = postprocess_answer_option_conditioned(pred)
> UnboundLocalError: local variable 'pred' referenced before assignment

**Comment by AllenShow** [comment]
and the similar issue for _postprocess_answer_option_conditioned(pred)_

```
Traceback (most recent call last):
  File "run_short_form.py", line 384, in <module>
    main()
  File "run_short_form.py", line 342, in main
    pred, results, do_retrieve = generate(
  File "run_short_form.py", line 326, in generate
    return call_model_rerank_w_scores_batch(prompt, evidences=evidences, model=model, max_new_tokens=max_new_tokens,
  File "run_short_form.py", line 192, in call_model_rerank_w_scores_batch
    postprocessed_pred = postprocess_answer_option_conditioned(pred)
UnboundLocalError: local variable 'pred' referenced before assignment
```
